version: '3.8'

services:
  db:
    build:
      context: ./db/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'db'
    ports:
      - "3307:3306"

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "sleep 3s; uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "3001:8000"
    depends_on:
      - db

volumes:
  mysql_data:
